language: generic
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  target_branch: gh-pages
  on:
    branch: master
env:
  global:
    secure: mIxd404Sx+OWg8ZI1Ar8jhv9advf33BNg+4R8hBYSiE4QvwxpwGPLw7xH2hGLJ5mOyr0i6tpgfiHkmxb2cHrWorNFKwKIXu5YROly8vxhTdCFYcT08BhY8Ix936SgsVYwrLzR1eOJUDEf6ZHcD5jbNXrosCTyuFTeMQvmmaLrqGhNGmRAbf6EwbWzfUMP+3xafoaQfrRlRHeeXM35BiRJOwffR/buoyjasAaXC0NKzsK5VUn7HoyjPsPXd2nI7/KBzv138Bfi5W42UwCsVUIBG7cTzL3Ny66p+UwFPum+77KtDNRKi1+iyPsLRR0wdlUDsopb5vcyNxYl077JzIEuzwV0a1sMKZYlnyny4zlIjtd7n/n37wfeXe3Z6aBa2DrShSV+a5WgmlfGUf1uWCmnflvz2JDdrgA0wkbzlQL4XLpp14vNOwZO7HeuU+ltn5PSVcgrCpUe9qiGS4GEagh8YU6aXi53etrzucz6MD6fsuG8SuI0s2b0Rx8Re4J/3A5lZugHlYQvHHJw+CYKFwKOqN007qrg/9+57u+scY3euVGVuzTPrU+py/HSOq7D3L7nYGZM694y47sBAOaQaVqHil/NcmTbXk5tY/I4yTnInTO8aNPvzVzvml/uv2u1pxOrUU4XZhDXoLtENb75ruYca01e+CjJi1UhHM1c/NkPAA=
