language: generic
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  target_branch: gh_pages
  on:
    branch: master
env:
  global:
    secure: jv2Y6uLtkxtxyWb/tgY+9HjN86eZ96R5s8f8wSHfnQI5FvQze2aUioI4Y+OCnamRoL81VYCkmB3HwngOiYXpw0UvBXpeFHpOJ/GPfyMMXPEkrNZHpMDo15dELBC6UNvtOTd8XsIn6WfaAxAdvqOonukDNyWdvnzf/7x8SCmFGDYqM/t9GlgTJo68Zf7lLJkUydS5CKL80oREaRFU4heovw5oSvwbXY2FcTyAqsPXD0Xh4/r6GbaDFGm78kI+lW6x3wrTpxO6eE1LfrArmTPoz2vJJRAsdLHvgyIp7jMw+oyOf2wyVxpzat+baJ3YkgTjOSSfUdq3EtybEvBp+Hll43YK0hhodCuzJf5uiqk0m0MkcngbPBhnNGL3MNuVYgPP2Dt8d8fPnnes8lrzQHht/5/U/i+uFaFZ0kOmHVIU6TYkl+MI80kUkdpTn7CHPvrvo5xmxCWc2fNT1/9mIbaEQE+BCBxYlQ66RzlfYFJzMVo4bkrcoalM2x5ipMQItlX10uIuen91kmcuxYUmuInfvn/je0DId5ao+eUZ1g+JqOFJXrAAYjOSlJt3m0Qr5zjgLSlmTAhL3nwlGgAlDy8og4FdUco2JYXNk/Vkw7C9g8hVWlE/zQfWo9Ey3foQAB+FjZV/Crg6rgCyL6bIsnyeOwIFI+XPnF54KH/oA+R3kiw=
